"""Permitir usuario sem empresa

Revision ID: 0927c34828b3
Revises: 9d06433ad7f5
Create Date: 2026-08-27 22:42:04.276004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0927c34828b3'
down_revision = '9d06433ad7f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('formas_pagamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('formas_pagamento', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_formas_pagamento_empresa_id'), ['empresa_id'], unique=False)

    op.create_table('taxas_pagamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('forma_pagamento_id', sa.Integer(), nullable=False),
    sa.Column('parcelas', sa.Integer(), nullable=False),
    sa.Column('percentual', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['forma_pagamento_id'], ['formas_pagamento.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('forma_pagamento_id', 'parcelas', name='uq_taxa_forma_pagamento_parcelas')
    )
    with op.batch_alter_table('taxas_pagamento', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_taxas_pagamento_forma_pagamento_id'), ['forma_pagamento_id'], unique=False)

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('empresa_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('vendas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('taxa_pagamento', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('percentual_taxa', sa.Numeric(precision=5, scale=2), nullable=True))
        batch_op.add_column(sa.Column('parcelas', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendas', schema=None) as batch_op:
        batch_op.drop_column('parcelas')
        batch_op.drop_column('percentual_taxa')
        batch_op.drop_column('taxa_pagamento')

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('empresa_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('taxas_pagamento', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_taxas_pagamento_forma_pagamento_id'))

    op.drop_table('taxas_pagamento')
    with op.batch_alter_table('formas_pagamento', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_formas_pagamento_empresa_id'))

    op.drop_table('formas_pagamento')
    # ### end Alembic commands ###
