"""Relacionamentos dos models

Revision ID: 9d06433ad7f5
Revises: c68c47c2b6f1
Create Date: 2026-07-15 22:32:41.102977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d06433ad7f5'
down_revision = 'c68c47c2b6f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categorias', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deletado_em', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_categorias_empresa_id'), ['empresa_id'], unique=False)

    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deletado_em', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_clientes_cpf_cnpj'), ['cpf_cnpj'], unique=False)
        batch_op.create_index(batch_op.f('ix_clientes_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_clientes_empresa_id'), ['empresa_id'], unique=False)

    with op.batch_alter_table('despesas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deletado_em', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_despesas_categoria_id'), ['categoria_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_despesas_empresa_id'), ['empresa_id'], unique=False)

    with op.batch_alter_table('empresas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nome', sa.String(length=150), nullable=False))
        batch_op.add_column(sa.Column('ativo', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('deletado_em', sa.DateTime(), nullable=True))
        batch_op.alter_column('cep',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=9),
               existing_nullable=True)
        batch_op.drop_constraint(batch_op.f('empresas_cnpj_key'), type_='unique')
        batch_op.drop_constraint(batch_op.f('empresas_email_key'), type_='unique')
        batch_op.create_index(batch_op.f('ix_empresas_cnpj'), ['cnpj'], unique=True)
        batch_op.create_index(batch_op.f('ix_empresas_email'), ['email'], unique=True)
        batch_op.drop_column('plano')
        batch_op.drop_column('nome_fantasia')
        batch_op.drop_column('status')
        batch_op.drop_column('razao_social')

    with op.batch_alter_table('funcionarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deletado_em', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_funcionarios_empresa_id'), ['empresa_id'], unique=False)

    with op.batch_alter_table('itens_orcamento', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_itens_orcamento_orcamento_id'), ['orcamento_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_itens_orcamento_produto_id'), ['produto_id'], unique=False)

    with op.batch_alter_table('itens_venda', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_itens_venda_produto_id'), ['produto_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_itens_venda_venda_id'), ['venda_id'], unique=False)

    with op.batch_alter_table('orcamentos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deletado_em', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_orcamentos_cliente_id'), ['cliente_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orcamentos_empresa_id'), ['empresa_id'], unique=False)

    with op.batch_alter_table('produtos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_produtos_categoria_id'), ['categoria_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_produtos_empresa_id'), ['empresa_id'], unique=False)

    with op.batch_alter_table('receitas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deletado_em', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_receitas_categoria_id'), ['categoria_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_receitas_cliente_id'), ['cliente_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_receitas_empresa_id'), ['empresa_id'], unique=False)

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deletado_em', sa.DateTime(), nullable=True))
        batch_op.alter_column('tipo',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=30),
               existing_nullable=False)
        batch_op.drop_constraint(batch_op.f('usuarios_email_key'), type_='unique')
        batch_op.create_index(batch_op.f('ix_usuarios_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_usuarios_empresa_id'), ['empresa_id'], unique=False)

    with op.batch_alter_table('vendas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deletado_em', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_vendas_cliente_id'), ['cliente_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vendas_empresa_id'), ['empresa_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vendas_empresa_id'))
        batch_op.drop_index(batch_op.f('ix_vendas_cliente_id'))
        batch_op.drop_column('deletado_em')

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuarios_empresa_id'))
        batch_op.drop_index(batch_op.f('ix_usuarios_email'))
        batch_op.create_unique_constraint(batch_op.f('usuarios_email_key'), ['email'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('tipo',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.drop_column('deletado_em')

    with op.batch_alter_table('receitas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_receitas_empresa_id'))
        batch_op.drop_index(batch_op.f('ix_receitas_cliente_id'))
        batch_op.drop_index(batch_op.f('ix_receitas_categoria_id'))
        batch_op.drop_column('deletado_em')

    with op.batch_alter_table('produtos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_produtos_empresa_id'))
        batch_op.drop_index(batch_op.f('ix_produtos_categoria_id'))

    with op.batch_alter_table('orcamentos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orcamentos_empresa_id'))
        batch_op.drop_index(batch_op.f('ix_orcamentos_cliente_id'))
        batch_op.drop_column('deletado_em')

    with op.batch_alter_table('itens_venda', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_itens_venda_venda_id'))
        batch_op.drop_index(batch_op.f('ix_itens_venda_produto_id'))

    with op.batch_alter_table('itens_orcamento', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_itens_orcamento_produto_id'))
        batch_op.drop_index(batch_op.f('ix_itens_orcamento_orcamento_id'))

    with op.batch_alter_table('funcionarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_funcionarios_empresa_id'))
        batch_op.drop_column('deletado_em')

    with op.batch_alter_table('empresas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('razao_social', sa.VARCHAR(length=150), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('nome_fantasia', sa.VARCHAR(length=150), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('plano', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.drop_index(batch_op.f('ix_empresas_email'))
        batch_op.drop_index(batch_op.f('ix_empresas_cnpj'))
        batch_op.create_unique_constraint(batch_op.f('empresas_email_key'), ['email'], postgresql_nulls_not_distinct=False)
        batch_op.create_unique_constraint(batch_op.f('empresas_cnpj_key'), ['cnpj'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('cep',
               existing_type=sa.String(length=9),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
        batch_op.drop_column('deletado_em')
        batch_op.drop_column('ativo')
        batch_op.drop_column('nome')

    with op.batch_alter_table('despesas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_despesas_empresa_id'))
        batch_op.drop_index(batch_op.f('ix_despesas_categoria_id'))
        batch_op.drop_column('deletado_em')

    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clientes_empresa_id'))
        batch_op.drop_index(batch_op.f('ix_clientes_email'))
        batch_op.drop_index(batch_op.f('ix_clientes_cpf_cnpj'))
        batch_op.drop_column('deletado_em')

    with op.batch_alter_table('categorias', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_categorias_empresa_id'))
        batch_op.drop_column('deletado_em')

    # ### end Alembic commands ###
