"""Adicionando taxa nas receitas

Revision ID: c2e2b615a3ab
Revises: 0927c34828b3
Create Date: 2026-09-18 16:40:58.336149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2e2b615a3ab'
down_revision = '0927c34828b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('receitas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('taxa_percentual', sa.Numeric(precision=5, scale=2), nullable=True))
        batch_op.add_column(sa.Column('taxa_valor', sa.Numeric(precision=10, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('receitas', schema=None) as batch_op:
        batch_op.drop_column('taxa_valor')
        batch_op.drop_column('taxa_percentual')

    # ### end Alembic commands ###
